from setuptools import setup, find_packages

setup(
    name="ai-humanizer",
    version="1.0.0",
    description="Open-source AI text humanization toolkit with 4 proven approaches",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    author="Lynote.ai",
    author_email="contact@lynote.ai",
    url="https://github.com/molly554/ai-humanize",
    project_urls={
        "Homepage": "https://lynote.ai",
        "Documentation": "https://github.com/molly554/ai-humanize/tree/main/docs",
        "Bug Tracker": "https://github.com/molly554/ai-humanize/issues",
    },
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "fastapi>=0.104.0",
        "uvicorn>=0.24.0",
        "httpx>=0.25.0",
        "toml>=0.10.2",
        "pydantic>=2.5.0",
        "deep-translator>=1.11.0",
        "transformers>=4.36.0",
        "torch>=2.1.0",
        "sentencepiece>=0.1.99",
        "nltk>=3.8.0",
        "langdetect>=1.0.9",
        "click>=8.1.0",
        "rich>=13.7.0",
    ],
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Text Processing :: Linguistic",
    ],
    keywords="ai humanize text rewriting nlp detection paraphrase",
)
